### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by AyanazKhaleghi** [Yasinrabiee/Persian-Dictionary#1]
سلام 
این دیکشنری تا چه حدی کامله؟
همه فعل‌هارو داره؟

**Comment by Yasinrabiee** [comment]
سلام
 تقریباً میشه گفت کامله
همه فعل‌ها که داخلش وجود ندارن چون اگر قرار باشه همه فعل‌ها وجود داشته باشن تعداد کلماتش به بالای سیصد هزارتا میرسه و حجمش بالا میره
ولی **_بن فعل‌ها_** داخلش موجوده...
